[tool.poetry]
name = "repl-nix-tgchatgptbot"
version = "0.1.0"
description = ""
authors = ["Your Name <you@example.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"
openai = "^1.46.1"
python-telegram-bot = "^21.6"
python-dotenv = "^1.0.1"
aiofiles = "^23.2.1"
aiosqlite = "^0.19.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
